In [34]:
#output
import pandas as pd
df = pd.read_csv('/Users/manavinair/Downloads/Sample Output - Sample Output.csv', index_col=False, delimiter = ',')
df

,event_timestamp,tag__id,tag__name,tag__desc,tag__value,tag__unit
0,05/08/2021 21:30:39,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),0.000000,mps
1,05/08/2021 21:30:49,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),38.372524,mps
2,05/08/2021 21:30:59,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),0.000000,mps
3,05/08/2021 21:31:09,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),27.673532,mps
4,05/08/2021 21:31:19,35827,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),0.000000,mps
...,...,...,...,...,...,...
109,05/08/2021 21:48:49,83540,L_R1_CNT_PASS0,R1 CONTROL PASS ZERO,0.000000,NaN
110,05/08/2021 21:48:59,83540,L_R1_CNT_PASS0,R1 CONTROL PASS ZERO,0.000000,NaN
111,05/08/2021 21:49:09,83540,L_R1_CNT_PASS0,R1 CONTROL PASS ZERO,0.000000,NaN
112,05/08/2021 21:49:19,83540,L_R1_CNT_PASS0,R1 CONTROL PASS ZERO,0.000000,NaN
113,05/08/2021 21:49:29,83540,L_R1_CNT_PASS0,R1 CONTROL PASS ZERO,1.000000,NaN

In [68]:
#input
import pandas as pd
df = pd.read_csv('/Users/manavinair/Downloads/Book1.csv', index_col=False, delimiter = ',')
df.rename(columns={'ItemId':'tag__id'}, inplace=True)
df.rename(columns={'ItemName':'tag__name'}, inplace=True)
df.rename(columns={'Comment':'tag__desc'}, inplace=True)
df=df.join(val)
#df.drop(['ComputerId'], axis=1, inplace=True)
#df['event_timestamp']=df['Date']+' '+df['Time']
df

,tag__id,ComputerId,tag__name,tag__desc,Unit,event_timestamp
0,35827,10,L_R1SDW_SPDREF,R1 Screw Down WS Speed Reference (mps),NaN,06-05-2022 21:58:33
1,35828,10,L_R1SDD_SPDREF,R1 Screw Down DS Speed Reference (mps),NaN,06-05-2022 21:58:33
2,35829,10,L_R1SDL_SPDREF,R1 Screw Down LS Speed Reference (mps),NaN,06-05-2022 21:58:33
3,35830,10,L_R1SDW_SPDFBK,R1 Screw Down WS Speed Feedback (mps),NaN,06-05-2022 21:58:33
4,35831,10,L_R1SDD_SPDFBK,R1 Screw Down DS Speed Feedback (mps),NaN,06-05-2022 21:58:33
5,35832,10,L_R1SDL_SPDFBK,R1 Screw Down LS Speed Feedback (mps),NaN,06-05-2022 21:58:33
6,35974,10,L_R1_ODG_AUX_B07,R1 ODG AUX output B07,NaN,06-05-2022 21:58:33
7,83528,10,RM1_RUNDOWN_ID_HS,R! RUNDOWN ID,NaN,06-05-2022 21:58:33
8,83530,10,L_R1SD_WS_GAP,R1 SCREW DOWN WORK SIDE GAP (MM),NaN,06-05-2022 21:58:33
9,83531,10,L_R1SD_DS_GAP,R1 SCREW DOWN DRIVE SIDE GAP (MM),NaN,06-05-2022 21:58:33
10,83532,10,L_R1SD_WS_SPDREF,R1 SCREW DOWN WS SPD REF (MPS),NaN,06-05-2022 21:58:33
11,83533,10,L_R1SD_DS_SPDREF,R1 SCREW DOWN DS SPD REF (MPS),NaN,06-05-2022 21:58:33
12,83534,10,L_R1SDLS_SPDREF,R1 SCREW DOWN LOW SPEED REF (MPS),NaN,06-05-2022 21:58:33
13,83535,10,L_R1SD_WS_SPDFBK,R1 SCREW DOWN WS SPEED FBK (MPS),NaN,06-05-2022 21:58:33
14,83536,10,L_R1SD_DS_SPDFBK,R1 SCREW DOWN DS SPEED FBK (MPS),NaN,06-05-2022 21:58:33
15,83537,10,L_R1SDLS_SPDFBK,R1 SCREW DOWN LS SPEED FBK (MPS),NaN,06-05-2022 21:58:33
16,83538,10,L_R1SD_WS_CUR,R1 SCREW DOWN WS CURRENT (%),NaN,06-05-2022 21:58:33
17,83539,10,L_R1SD_DS_CUR,R1 SCREW DOWN DS CURRENT (%),NaN,06-05-2022 21:58:33
18,83540,10,L_R1_CNT_PASS0,R1 CONTROL PASS ZERO,NaN,06-05-2022 21:58:33

In [65]:
#input
import pandas as pd
df1 = pd.read_csv('/Users/manavinair/Downloads/Sample Input2.csv', index_col=False, delimiter = ',')
#df.rename(columns={'ItemId':'Tag__id'}, inplace=True)
#df.drop(['Date','Time'], axis=1, inplace=True)
val=df1['event_timestamp']=df1['Date'].astype(str)+' '+df1['Time']
val=df1['event_timestamp']
df1

             Date      Time  Milli Sec      event_timestamp
0      06-05-2022  21:58:33      140.0  06-05-2022 21:58:33
1      06-05-2022  21:58:33      145.0  06-05-2022 21:58:33
2      06-05-2022  21:58:33      150.0  06-05-2022 21:58:33
3      06-05-2022  21:58:33      155.0  06-05-2022 21:58:33
4      06-05-2022  21:58:33      160.0  06-05-2022 21:58:33
...           ...       ...        ...                  ...
12766         NaN       NaN        NaN                  NaN
12767         NaN       NaN        NaN                  NaN
12768         NaN       NaN        NaN                  NaN
12769         NaN       NaN        NaN                  NaN
12770         NaN       NaN        NaN                  NaN

[12771 rows x 4 columns]

In [60]:
df['event_timestamp']

0        06-05-2022 21:58:33
1        06-05-2022 21:58:33
2        06-05-2022 21:58:33
3        06-05-2022 21:58:33
4        06-05-2022 21:58:33
                ...
12766                    NaN
12767                    NaN
12768                    NaN
12769                    NaN
12770                    NaN
Name: event_timestamp, Length: 12771, dtype: object